# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LS', '0002_code_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='task_name',
            field=models.TextField(),
        ),
    ]
